version: "3"
services:
  # Alacris services
  alacris_mkb: # Alacris MKB
    build:
      context: ..
      dockerfile: docker/containers/alacris_mkb/Dockerfile
    image: gcr.io/legicash-demo-1950/legicash-demo/alacris_mkb:${TAG:-v1.1}
    hostname: "alacris-mkb"
    container_name: "alacris-mkb"
    networks:
      legicash-demo:
        ipv4_address: 10.5.0.11
    ports:
      - "8805:8805"
      - "8806:8806"


networks:
  legicash-demo:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/24
